### ISSUE TITLE
Private webhook makes WEBHOOK_URL unavailable to forked PRs

### ISSUE THREAD

**Issue by ldilley** [DiscordHooks/travis-ci-discord-webhook#13]
This is related to #2. My team just started using this project yesterday and it works great for pushes to the branch. However, we also want to receive Discord pass/fail notifications for builds from forked pull requests. Currently, the `WEBHOOK_URL` is empty to PRs from forks. This is by design per https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings.

Considering the aim of this project is to get notifications to Discord, is there any way around this other than adding the webhook URL to `.travis.yml`? This will make the webhook URL available to forks, but is also potentially insecure.

Thank you for any insight that you can offer.

**Comment by k3rn31p4nic** [comment]
According to the [Travis CI docs](https://docs.travis-ci.com/user/environment-variables), env vars can only be declared in Travis config file (`.travis.yml`) & Travis repo settings.

The script currently uses Travis repo settings, so that it won't be visible to others. Which also means, it won't be available to the PRs coming from other repos (forks).

So, the only way to make it available to forks is to declared in the Travis config file without encrypting it, because encrypted variables are not available to forks either. Which means, the webhook URL will be exposed to other repos and they can spam data to the Discord channel which is associated with the webhook by just opening a PR.

**Comment by ldilley** [comment]
Thank you very much for the prompt response, @k3rn31p4nic. I figured that was the case, but wanted to see if anyone had a safer alternative. We do not mind the traffic from legitimate PRs. The main concern is people targeting the Discord hook directly and sending arbitrary messages unrelated to GitHub and Travis.
